/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    'menu-items': MenuItem;
    tiers: Tier;
    'weekly-menus': WeeklyMenu;
    orders: Order;
    'kitchen-orders': KitchenOrder;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    tiers: TiersSelect<false> | TiersSelect<true>;
    'weekly-menus': WeeklyMenusSelect<false> | WeeklyMenusSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'kitchen-orders': KitchenOrdersSelect<false> | KitchenOrdersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'editor' | 'user')[] | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Customer pricing tier
   */
  tier?: (number | null) | Tier;
  /**
   * Current credit balance
   */
  credit_balance?: number | null;
  /**
   * Credit balance expiration date
   */
  credit_bal_exp?: string | null;
  active?: boolean | null;
  /**
   * Whether the customer has completed their preference setup
   */
  preferences_set?: boolean | null;
  /**
   * Weekly or monthly subscription
   */
  subscription_frequency?: string | null;
  /**
   * Number of meals per week
   */
  meals_per_week?: number | null;
  /**
   * Include breakfast in subscription
   */
  include_breakfast?: boolean | null;
  /**
   * Include snacks in subscription
   */
  include_snacks?: boolean | null;
  /**
   * Customer allergies
   */
  allergies?: string[] | null;
  /**
   * Which half of the week customer prefers for pickup
   */
  week_half?: ('firstHalf' | 'secondHalf') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiers".
 */
export interface Tier {
  id: number;
  tier_name: string;
  description?: string | null;
  monthly_price: number;
  weekly_price: number;
  single_price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  description: string;
  /**
   * Price for snacks only (a la carte). Meals are priced by tier subscription.
   */
  price?: number | null;
  category: 'lunch' | 'dinner' | 'premium' | 'breakfast-small' | 'breakfast-large' | 'dessert' | 'salad' | 'snack';
  active?: boolean | null;
  allergens?:
    | {
        allergen?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select which half of the week this menu item is available. Salads and snacks can be available for both halves.
   */
  availability?: {
    firstHalf?: boolean | null;
    secondHalf?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-menus".
 */
export interface WeeklyMenu {
  id: number;
  weekLabel: string;
  startDate: string;
  endDate: string;
  active?: boolean | null;
  firstHalfItems?:
    | {
        menuItem: number | MenuItem;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  secondHalfItems?:
    | {
        menuItem: number | MenuItem;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | Customer;
  status: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'completed' | 'cancelled';
  orderItems?:
    | {
        menuItem: number | MenuItem;
        quantity: number;
        /**
         * Which half of the week this item is for
         */
        weekHalf?: ('firstHalf' | 'secondHalf') | null;
        /**
         * Individual meal price (0 for tier-based subscriptions)
         */
        unitPrice?: number | null;
        /**
         * Total price for this item (0 for tier-based subscriptions)
         */
        totalPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  /**
   * Customer tier at time of order
   */
  tier?: (number | null) | Tier;
  subscriptionFrequency?: ('weekly' | 'monthly' | 'a_la_carte') | null;
  /**
   * Number of meals per week for this order
   */
  mealsPerWeek?: number | null;
  /**
   * Which half(s) of the week this order is for (both if meals from both halves)
   */
  weekHalf?: ('firstHalf' | 'secondHalf' | 'both') | null;
  /**
   * Additional notes for this order
   */
  notes?: string | null;
  allergenCharges?:
    | {
        mealId: string;
        mealName: string;
        quantity: number;
        matchingAllergens?:
          | {
              allergen: string;
              /**
               * Allergen charge (for tracking purposes, actual charge is $5.00 per order)
               */
              charge: number;
              id?: string | null;
            }[]
          | null;
        /**
         * Total allergen charge for this meal
         */
        totalAllergenCharge: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Total allergen charges for entire order
   */
  totalAllergenCharges: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kitchen-orders".
 */
export interface KitchenOrder {
  id: number;
  /**
   * Reference to original order
   */
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  /**
   * Customer phone number (optional)
   */
  customerPhone?: string | null;
  weekHalf: 'firstHalf' | 'secondHalf' | 'both';
  orderItems: {
    mealName: string;
    quantity: number;
    allergens?:
      | {
          allergen?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  allergenCharges?:
    | {
        mealName: string;
        allergens?:
          | {
              allergen: string;
              id?: string | null;
            }[]
          | null;
        charge: number;
        id?: string | null;
      }[]
    | null;
  totalAllergenCharges: number;
  /**
   * Calculated pickup date based on week half
   */
  pickupDate?: string | null;
  status: 'pending' | 'preparing' | 'ready' | 'completed';
  /**
   * Additional notes for kitchen
   */
  notes?: string | null;
  /**
   * Aggregated meal quantities by tier
   */
  tierAggregation?:
    | {
        tierName: string;
        tierId?: string | null;
        meals?:
          | {
              mealName: string;
              quantity: number;
              category?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Customer-specific allergen adjustments
   */
  allergenAdjustments?:
    | {
        customerName: string;
        allergens?:
          | {
              allergen?: string | null;
              id?: string | null;
            }[]
          | null;
        meals?:
          | {
              mealName: string;
              /**
               * Description of allergen adjustment (e.g., "without cheese")
               */
              adjustment?: string | null;
              quantity: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'tiers';
        value: number | Tier;
      } | null)
    | ({
        relationTo: 'weekly-menus';
        value: number | WeeklyMenu;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'kitchen-orders';
        value: number | KitchenOrder;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  tier?: T;
  credit_balance?: T;
  credit_bal_exp?: T;
  active?: T;
  preferences_set?: T;
  subscription_frequency?: T;
  meals_per_week?: T;
  include_breakfast?: T;
  include_snacks?: T;
  allergies?: T;
  week_half?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  category?: T;
  active?: T;
  allergens?:
    | T
    | {
        allergen?: T;
        id?: T;
      };
  availability?:
    | T
    | {
        firstHalf?: T;
        secondHalf?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiers_select".
 */
export interface TiersSelect<T extends boolean = true> {
  tier_name?: T;
  description?: T;
  monthly_price?: T;
  weekly_price?: T;
  single_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-menus_select".
 */
export interface WeeklyMenusSelect<T extends boolean = true> {
  weekLabel?: T;
  startDate?: T;
  endDate?: T;
  active?: T;
  firstHalfItems?:
    | T
    | {
        menuItem?: T;
        available?: T;
        id?: T;
      };
  secondHalfItems?:
    | T
    | {
        menuItem?: T;
        available?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  status?: T;
  orderItems?:
    | T
    | {
        menuItem?: T;
        quantity?: T;
        weekHalf?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  subtotal?: T;
  taxAmount?: T;
  totalAmount?: T;
  tier?: T;
  subscriptionFrequency?: T;
  mealsPerWeek?: T;
  weekHalf?: T;
  notes?: T;
  allergenCharges?:
    | T
    | {
        mealId?: T;
        mealName?: T;
        quantity?: T;
        matchingAllergens?:
          | T
          | {
              allergen?: T;
              charge?: T;
              id?: T;
            };
        totalAllergenCharge?: T;
        id?: T;
      };
  totalAllergenCharges?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kitchen-orders_select".
 */
export interface KitchenOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  weekHalf?: T;
  orderItems?:
    | T
    | {
        mealName?: T;
        quantity?: T;
        allergens?:
          | T
          | {
              allergen?: T;
              id?: T;
            };
        id?: T;
      };
  allergenCharges?:
    | T
    | {
        mealName?: T;
        allergens?:
          | T
          | {
              allergen?: T;
              id?: T;
            };
        charge?: T;
        id?: T;
      };
  totalAllergenCharges?: T;
  pickupDate?: T;
  status?: T;
  notes?: T;
  tierAggregation?:
    | T
    | {
        tierName?: T;
        tierId?: T;
        meals?:
          | T
          | {
              mealName?: T;
              quantity?: T;
              category?: T;
              id?: T;
            };
        id?: T;
      };
  allergenAdjustments?:
    | T
    | {
        customerName?: T;
        allergens?:
          | T
          | {
              allergen?: T;
              id?: T;
            };
        meals?:
          | T
          | {
              mealName?: T;
              adjustment?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}